=== KDE/tellico/tellico.dtd
<!--
   ================================================================
   Tellico XML DTD version 11.0

   Copyright (c) 2006-2009 Robby Stephenson

   This DTD describes the XML data files for the
   Tellico application, which can be found at:
   http://www.periapsis.org/tellico/

   The formal public identifer for this DTD should be:

      "-//Robby Stephenson/DTD Tellico V11.0//EN"

   ================================================================
-->
<!ELEMENT tellico (collection+, borrowers?, filters?)>
<!ATTLIST tellico syntaxVersion CDATA #FIXED "11">
<!ATTLIST tellico xmlns CDATA #FIXED "http://periapsis.org/tellico/">

<!ELEMENT collection (fields | bibtex-preamble | macros | entry |
images | borrowers | filters)+>
<!ATTLIST collection title CDATA #REQUIRED>
<!ATTLIST collection type (1|2|3|4|5|6|7|8|9|10|11|12|13) #REQUIRED>
<!ATTLIST collection entryTitle CDATA #IMPLIED>

<!ELEMENT images (image+)>
<!ELEMENT image (#PCDATA)>
<!ATTLIST image id CDATA #IMPLIED>
<!ATTLIST image format CDATA #IMPLIED>
<!ATTLIST image width CDATA #IMPLIED>
<!ATTLIST image height CDATA #IMPLIED>

<!ELEMENT fields (field+)>
<!ELEMENT field (prop*)>
<!ATTLIST field i18n (true|false) "true">
<!ATTLIST field name CDATA #REQUIRED>
<!ATTLIST field title CDATA #REQUIRED>
<!ATTLIST field category CDATA #REQUIRED>
<!ATTLIST field allowed CDATA #IMPLIED>
<!ATTLIST field flags CDATA #IMPLIED>
<!ATTLIST field format CDATA #IMPLIED>
<!ATTLIST field description CDATA #IMPLIED>
<!-- no 5, 9, 11, or 13 -->
<!ATTLIST field type (1|2|3|4|6|7|8|10|12|14) #REQUIRED>

<!ELEMENT prop (#PCDATA)>
<!ATTLIST prop name CDATA #REQUIRED>

<!-- bibliography, or bibtex, collections may have a preamble and macros -->
<!ELEMENT bibtex-preamble (#PCDATA)>
<!ELEMENT macros (macro+)>
<!ELEMENT macro (#PCDATA)>
<!ATTLIST macro name CDATA #REQUIRED>

<!-- general -->
<!-- columns are used in 2-column tables to split the values -->
<!ELEMENT column (#PCDATA)>
<!-- year, month, day are used in dates -->
<!ELEMENT year (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT day (#PCDATA)>

<!-- borrowing -->
<!ELEMENT borrowers (borrower+)>
<!ELEMENT borrower (loan)>
<!ELEMENT loan (#PCDATA)>
<!ATTLIST loan dueDate CDATA #IMPLIED>
<!ATTLIST loan loanDate CDATA #REQUIRED>
<!ATTLIST loan entryRef CDATA #REQUIRED>
<!ATTLIST loan uid CDATA #REQUIRED>

<!-- filters -->
<!ELEMENT filters (filter+)>
<!ELEMENT filter (rule)>
<!ATTLIST filter name CDATA #REQUIRED>
<!ATTLIST filter match CDATA #REQUIRED>
<!ELEMENT rule (#PCDATA)>
<!ATTLIST rule field CDATA #REQUIRED>
<!ATTLIST rule function CDATA #REQUIRED>
<!ATTLIST rule pattern CDATA #REQUIRED>

<!ELEMENT entry (id | title | subtitle | authors | binding | pur_date |
pur_price | publisher | edition | cr_years | pub_year | isbn | lccn |
pages | languages | genres | keywords | series | series_num |
condition | signed | read | gift | loaned | rating | comments |
entry-type | bibtex-key | booktitle | editors | organization | years | year |
journal | month | number | howpublished | chapter | volume | crossref |
note | medium | artists | album | labels | label | tracks | certification |
region | nationalitys | format | casts | directors | producers |
writers | composers | studios | subtitles | audio-tracks |
running-time | aspect-ratios | widescreen | color | directors-cut |
plot | players | player | team | brand | location | quantity | front | back |
mintmark | set | grade | service | obverse | reverse | issues| issue | cover |
description | scott | cancelled | hinged | centering | gummed |
producer | appellation | varietal | vintage | type | drink-by |
platform | publishers | developers | completed | url |
mimetype | size | permissions | owner | group | created | modified |
metainfos | icon | amazon | imdb | imdb-rating | alttitles |
allcertifications | address | abstract | designers | designer | bggid |
mechanisms | num-players | cdate | mdate | translators | currency |
countrys | country | doi | folder | denomination | image | playing-time | minimum-age)+>
<!ATTLIST entry id CDATA #REQUIRED>

<!-- general -->
<!ELEMENT id (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT mdate (year, month, day)>
<!ATTLIST mdate calendar CDATA #REQUIRED>
<!ELEMENT cdate (year, month, day)>
<!ATTLIST cdate calendar CDATA #REQUIRED>

<!-- books -->
<!ELEMENT subtitle (#PCDATA)>
<!ELEMENT authors (author+)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT binding (#PCDATA)>
<!ELEMENT pur_date (#PCDATA)>
<!ELEMENT pur_price (#PCDATA)>
<!ELEMENT publisher (#PCDATA)>
<!ELEMENT edition (#PCDATA)>
<!ELEMENT cr_years (cr_year+)>
<!ELEMENT cr_year (#PCDATA)>
<!ELEMENT pub_year (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT lccn (#PCDATA)>
<!ELEMENT pages (#PCDATA)>
<!ELEMENT languages (language+)>
<!ELEMENT language (#PCDATA)>
<!ELEMENT genres (genre+)>
<!ELEMENT genre (#PCDATA)>
<!ELEMENT keywords (keyword+)>
<!ELEMENT keyword (#PCDATA)>
<!ELEMENT series (#PCDATA)>
<!ELEMENT series_num (#PCDATA)>
<!ELEMENT condition (#PCDATA)>
<!ELEMENT signed (#PCDATA)>
<!ELEMENT read (#PCDATA)>
<!ELEMENT gift (#PCDATA)>
<!ELEMENT rating (#PCDATA)>
<!ELEMENT loaned (#PCDATA)>
<!ELEMENT comments (#PCDATA)>
<!ELEMENT translators (translator+)>
<!ELEMENT translator (#PCDATA)>

<!-- bibtex -->
<!ELEMENT entry-type (#PCDATA)>
<!ELEMENT bibtex-key (#PCDATA)>
<!ELEMENT booktitle (#PCDATA)>
<!ELEMENT editors (editor+)>
<!ELEMENT editor (#PCDATA)>
<!ELEMENT organization (#PCDATA)>
<!ELEMENT journal (#PCDATA)>
<!ELEMENT number (#PCDATA)>
<!ELEMENT howpublished (#PCDATA)>
<!ELEMENT chapter (#PCDATA)>
<!ELEMENT volume (#PCDATA)>
<!ELEMENT crossref (#PCDATA)>
<!ELEMENT note (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT abstract (#PCDATA)>
<!ELEMENT doi (#PCDATA)>

<!-- music -->
<!ELEMENT medium (#PCDATA)>
<!ELEMENT artists (artist+)>
<!ELEMENT artist (#PCDATA)>
<!ELEMENT album (#PCDATA)>
<!ELEMENT labels (label+)>
<!ELEMENT label (#PCDATA)>
<!ELEMENT tracks (track+)>
<!ELEMENT track (column+)>

<!-- video -->
<!ELEMENT certification (#PCDATA)>
<!ELEMENT region (#PCDATA)>
<!ELEMENT nationalitys (nationality+)>
<!ELEMENT nationality (#PCDATA)>
<!ELEMENT format (#PCDATA)>
<!ELEMENT casts (cast+)>
<!ELEMENT cast (column+)>
<!ELEMENT directors (director+)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT producers (producer+)>
<!ELEMENT producer (#PCDATA)>
<!ELEMENT writers (writer+)>
<!ELEMENT writer (#PCDATA)>
<!ELEMENT composers (composer+)>
<!ELEMENT composer (#PCDATA)>
<!ELEMENT studios (studio+)>
<!ELEMENT studio (#PCDATA)>
<!ELEMENT subtitles (subtitle+)>
<!-- subtitle element is defined above -->
<!ELEMENT audio-tracks (audio-track+)>
<!ELEMENT audio-track (#PCDATA)>
<!ELEMENT running-time (#PCDATA)>
<!ELEMENT aspect-ratios (aspect-ratio+)>
<!ELEMENT aspect-ratio (#PCDATA)>
<!ELEMENT widescreen (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT directors-cut (#PCDATA)>
<!ELEMENT plot (#PCDATA)>

<!-- cards -->
<!-- Before Tellico 2.3.10, player was singular -->
<!ELEMENT players (player+)>
<!ELEMENT player (#PCDATA)>
<!ELEMENT team (#PCDATA)>
<!ELEMENT brand (#PCDATA)>
<!ELEMENT location (#PCDATA)>
<!ELEMENT quantity (#PCDATA)>
<!ELEMENT front (#PCDATA)>
<!ELEMENT back (#PCDATA)>

<!-- coins -->
<!ELEMENT mintmark (#PCDATA)>
<!ELEMENT set (#PCDATA)>
<!ELEMENT grade (#PCDATA)>
<!ELEMENT service (#PCDATA)>
<!ELEMENT obverse (#PCDATA)>
<!ELEMENT reverse (#PCDATA)>
<!ELEMENT denomination (#PCDATA)>
<!ELEMENT country (#PCDATA)>
<!ELEMENT currency (#PCDATA)>

<!-- comic book -->
<!ELEMENT countrys (country+)>
<!ELEMENT issues (issue+)>
<!ELEMENT issue (#PCDATA)>
<!ELEMENT cover (#PCDATA)>

<!-- stamps -->
<!ELEMENT description (#PCDATA)>
<!ELEMENT scott (#PCDATA)>
<!ELEMENT cancelled (#PCDATA)>
<!ELEMENT hinged (#PCDATA)>
<!ELEMENT centering (#PCDATA)>
<!ELEMENT gummed (#PCDATA)>
<!ELEMENT years (year+)>

<!-- wine -->
<!ELEMENT appellation (#PCDATA)>
<!ELEMENT varietal (#PCDATA)>
<!ELEMENT vintage (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT drink-by (#PCDATA)>

<!-- games -->
<!ELEMENT platform (#PCDATA)>
<!-- publisher is defined above -->
<!ELEMENT publishers (publisher+)>
<!ELEMENT developers (developer+)>
<!ELEMENT developer (#PCDATA)>
<!ELEMENT completed (#PCDATA)>

<!-- file catalogs -->
<!-- description is above -->
<!ELEMENT url (#PCDATA)>
<!ELEMENT folder (#PCDATA)>
<!ELEMENT mimetype (#PCDATA)>
<!ELEMENT size (#PCDATA)>
<!ELEMENT permissions (#PCDATA)>
<!ELEMENT owner (#PCDATA)>
<!ELEMENT group (#PCDATA)>
<!ELEMENT created (#PCDATA)>
<!ELEMENT modified (#PCDATA)>
<!ELEMENT metainfos (metainfo+)>
<!ELEMENT metainfo (column+)>
<!ELEMENT icon (#PCDATA)>

<!-- boardgames -->
<!-- publisher is defined above -->
<!-- publishers is defined above -->
<!ELEMENT designers (designer+)>
<!ELEMENT designer (#PCDATA)>
<!ELEMENT mechanisms (mechanism+)>
<!ELEMENT mechanism (#PCDATA)>
<!ELEMENT bggid (#PCDATA)>
<!ELEMENT num-players (num-player+)>
<!ELEMENT num-player (#PCDATA)>
<!-- playing-time and minimum-age added for Tellico v3 -->
<!ELEMENT playing-time (#PCDATA)>
<!ELEMENT minimum-age (#PCDATA)>

<!-- special -->
<!ELEMENT amazon (#PCDATA)>
<!ELEMENT imdb (#PCDATA)>
<!ELEMENT imdb-rating (#PCDATA)>
<!ELEMENT alttitles (alttitle+)>
<!ELEMENT alttitle (column)>
<!ELEMENT altcertifications (altcertification+)>
<!ELEMENT altcertification (column)>

=== KDE/tellico/src/tests/data/relative-link.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tellico PUBLIC '-//Robby Stephenson/DTD Tellico V11.0//EN' 'http://periapsis.org/tellico/dtd/v11/tellico.dtd'>
<tellico xmlns="http://periapsis.org/tellico/" syntaxVersion="11">
 <collection type="1" title="My Collection">
  <fields>
   <field category="Personal" flags="32" type="6" description="" name="id" format="4" title="ID">
    <prop name="template">%{@id}</prop>
   </field>
   <field category="General" flags="8" type="1" description="" name="title" format="1" title="Title"/>
   <field category="General" flags="0" type="7" description="New Field 1" name="url" format="4" title="URL">
    <prop name="relative">true</prop>
   </field>
  </fields>
  <entry id="1">
   <id>1</id>
   <title>test</title>
   <url>collectorz/image.png</url>
  </entry>
 </collection>
</tellico>

=== KDE/tellico/src/tests/data/bug521148.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tellico PUBLIC '-//Robby Stephenson/DTD Tellico V11.0//EN' 'http://periapsis.org/tellico/dtd/v11/tellico.dtd'>
<tellico xmlns="http://periapsis.org/tellico/" syntaxVersion="11">
 <collection title="My Collection" type="1">
  <fields>
   <field category="Personal" flags="32" format="4" name="id" title="ID" type="6">
    <prop name="template">%{@id}</prop>
   </field>
   <field category="General" flags="8" format="1" name="title" title="Title" type="1"/>
   <field category="Personal" flags="16" format="3" name="cdate" title="Date Created" type="12"/>
   <field category="Personal" flags="16" format="3" name="mdate" title="Date Modified" type="12"/>
   <field category="General" description="New Field 1" flags="0" format="4" name="test-😭" title="test 😭" type="4"/>
  </fields>
  <entry id="1">
   <id>1</id>
   <title>test</title>
   <cdate calendar="gregorian">
    <year>2026</year>
    <month>06</month>
    <day>28</day>
   </cdate>
   <mdate calendar="gregorian">
    <year>2026</year>
    <month>06</month>
    <day>28</day>
   </mdate>
   <test-😭>true</test-😭>
  </entry>
 </collection>
</tellico>

=== KDE/tellico/src/tests/data/image_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tellico PUBLIC '-//Robby Stephenson/DTD Tellico V11.0//EN' 'http://periapsis.org/tellico/dtd/v11/tellico.dtd'>
<tellico xmlns="http://periapsis.org/tellico/" syntaxVersion="11">
 <collection title="My Books" type="2">
  <fields>
   <field title="Title" flags="8" category="General" format="1" type="1" name="title"/>
   <field title="Front Cover" flags="0" category="Front Cover" format="4" type="10" name="cover"/>
  </fields>
  <entry id="1">
   <title>book1</title>
   <cover>%COVER%</cover>
  </entry>
 </collection>
</tellico>

=== KDE/tellico/src/tests/data/no_cdate.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tellico PUBLIC '-//Robby Stephenson/DTD Tellico V11.0//EN' 'http://periapsis.org/tellico/dtd/v11/tellico.dtd'>
<tellico xmlns="http://periapsis.org/tellico/" syntaxVersion="11">
 <collection title="No CDate Music" type="4">
  <fields>
   <field name="_default"/>
  </fields>
  <entry id="2">
   <title>CDate Test</title>
   <!-- SpaceX Crew Dragon Demo-2 launch date -->
   <mdate calendar="gregorian">
    <year>2020</year>
    <month>05</month>
    <day>30</day>
   </mdate>
  </entry>
 </collection>
</tellico>

=== KDE/tellico/src/tests/data/bug443845.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tellico PUBLIC '-//Robby Stephenson/DTD Tellico V11.0//EN' 'http://periapsis.org/tellico/dtd/v11/tellico.dtd'>
<tellico xmlns="http://periapsis.org/tellico/" syntaxVersion="11">
 <collection title="Book Collection" type="2">
  <fields>
   <field title="Title" flags="6" name="title" category="General" format="1" type="1"/>
   <field title="Description" description="Description" flags="0" name="description" category="Description" format="4" type="2"/>
  </fields>
  <entry id="21215">
   <title>Control Character</title>
   <description>This has a controol character in it&lt;br/>&lt;br/>&lt;br/>&lt;br/></description>
  </entry>
 </collection>
</tellico>

=== KDE/tellico/src/tests/data/duplicate_loan.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tellico PUBLIC '-//Robby Stephenson/DTD Tellico V11.0//EN' 'http://periapsis.org/tellico/dtd/v11/tellico.dtd'>
<tellico xmlns="http://periapsis.org/tellico/" syntaxVersion="11">
 <collection title="My Books" type="2">
  <fields>
   <field title="Title" flags="8" category="General" format="1" type="1" name="title"/>
   <field title="Subtitle" flags="0" category="General" format="1" type="1" name="subtitle"/>
   <field title="Author" flags="7" category="General" format="2" type="1" name="author"/>
   <field title="Editor" flags="7" category="General" format="2" type="1" name="editor"/>
   <field title="Binding" flags="2" category="General" format="4" type="3" allowed="Hardback;Paperback;Trade Paperback;E-Book;Magazine;Journal" name="binding"/>
   <field title="Purchase Date" flags="0" category="General" format="3" type="1" name="pur_date"/>
   <field title="Purchase Price" flags="0" category="General" format="4" type="1" name="pur_price"/>
   <field title="Publisher" flags="6" category="Publishing" format="0" type="1" name="publisher"/>
   <field title="Edition" flags="4" category="Publishing" format="0" type="1" name="edition"/>
   <field title="Copyright Year" flags="3" category="Publishing" format="4" type="6" name="cr_year"/>
   <field title="Publication Year" flags="2" category="Publishing" format="4" type="6" name="pub_year"/>
   <field title="ISBN#" flags="0" category="Publishing" format="4" description="International Standard Book Number" type="1" name="isbn"/>
   <field title="LCCN#" flags="0" category="Publishing" format="4" description="Library of Congress Control Number" type="1" name="lccn"/>
   <field title="Pages" flags="0" category="Publishing" format="4" type="6" name="pages"/>
   <field title="Translator" flags="7" category="Publishing" format="2" type="1" name="translator"/>
   <field title="Language" flags="7" category="Publishing" format="4" type="1" name="language"/>
   <field title="Genre" flags="7" category="Classification" format="4" type="1" name="genre"/>
   <field title="Keywords" flags="7" category="Classification" format="4" type="1" name="keyword"/>
   <field title="Series" flags="6" category="Classification" format="4" type="1" name="series"/>
   <field title="Series Number" flags="0" category="Classification" format="4" type="6" name="series_num"/>
   <field title="Condition" flags="0" category="Classification" format="4" type="3" allowed="New;Used" name="condition"/>
   <field title="Signed" flags="0" category="Personal" format="4" type="4" name="signed"/>
   <field title="Read" flags="0" category="Personal" format="4" type="4" name="read"/>
   <field title="Gift" flags="0" category="Personal" format="4" type="4" name="gift"/>
   <field title="Loaned" flags="0" category="Personal" format="4" type="4" name="loaned"/>
   <field title="Rating" flags="2" category="Personal" format="4" type="14" name="rating">
    <prop name="maximum">5</prop>
    <prop name="minimum">1</prop>
   </field>
   <field title="Front Cover" flags="0" category="Front Cover" format="4" type="10" name="cover"/>
   <field title="Comments" flags="0" category="Comments" format="4" type="2" name="comments"/>
   <field title="ID" flags="32" category="Personal" format="4" type="6" name="id">
    <prop name="template">%{@id}</prop>
   </field>
   <field title="Date Created" flags="16" category="Personal" format="3" type="12" name="cdate"/>
   <field title="Date Modified" flags="16" category="Personal" format="3" type="12" name="mdate"/>
  </fields>
  <entry id="1">
   <title>book1</title>
   <loaned>true</loaned>
   <id>1</id>
   <cdate calendar="gregorian">
    <year>2012</year>
    <month>10</month>
    <day>07</day>
   </cdate>
   <mdate calendar="gregorian">
    <year>2012</year>
    <month>10</month>
    <day>12</day>
   </mdate>
  </entry>
  <entry id="2">
   <title>book2</title>
   <id>2</id>
   <cdate calendar="gregorian">
    <year>2012</year>
    <month>10</month>
    <day>07</day>
   </cdate>
   <mdate calendar="gregorian">
    <year>2012</year>
    <month>10</month>
    <day>12</day>
   </mdate>
  </entry>
  <entry id="3">
   <title>book3</title>
   <id>3</id>
   <cdate calendar="gregorian">
    <year>2012</year>
    <month>10</month>
    <day>07</day>
   </cdate>
   <mdate calendar="gregorian">
    <year>2012</year>
    <month>10</month>
    <day>12</day>
   </mdate>
  </entry>
  <entry id="4">
   <title>book4</title>
   <id>4</id>
   <cdate calendar="gregorian">
    <year>2012</year>
    <month>10</month>
    <day>07</day>
   </cdate>
   <mdate calendar="gregorian">
    <year>2012</year>
    <month>10</month>
    <day>12</day>
   </mdate>
  </entry>
 </collection>
 <borrowers>
  <borrower uid="ZnpWj3co6o" name="Ashley Stephenson">
   <loan loanDate="2012-10-12" dueDate="" uid="Tellico5oLyJpEvpoX24" entryRef="1"></loan>
  </borrower>
  <borrower uid="ZnpWj3co6o" name="Ashley Stephenson">
   <loan loanDate="2012-10-12" dueDate="" uid="Tellico5oLyJpEvpoX24" entryRef="1"></loan>
  </borrower>
 </borrowers>
</tellico>
